import { useState, useEffect } from 'react'
import { createPortal } from 'react-dom'
import { motion, AnimatePresence } from 'framer-motion'
import { getTeamForEra } from '../engine/teamUtils'
import TeamLogo from './TeamLogo'
import CardExpanded from './CardExpanded'

// ─── Rarity ──────────────────────────────────────────────────────────────────

const RARITY = {
  common:   { label: 'Common',   color: '#9ca3af', glow: 'none' },
  uncommon: { label: 'Uncommon', color: '#34d399', glow: '0 0 8px rgba(52,211,153,0.35)' },
  rare:     { label: 'Rare',     color: '#818cf8', glow: '0 0 14px rgba(129,140,248,0.5)' },
  legend:   { label: 'LEGEND',   color: '#f59e0b', glow: '0 0 22px rgba(245,158,11,0.65)' },
}

// ─── Tool helpers ─────────────────────────────────────────────────────────────

const TOOL_COLS = [
  { key: 'avg_tool',      label: 'AVG' },
  { key: 'power_tool',    label: 'PWR' },
  { key: 'speed_tool',    label: 'SPD' },
  { key: 'fielding_tool', label: 'FLD' },
  { key: 'arm_tool',      label: 'ARM' },
]

function toolColor(v) {
  if (v >= 80) return '#22c55e'
  if (v >= 65) return '#86efac'
  if (v >= 50) return '#fbbf24'
  if (v >= 35) return '#f97316'
  return '#ef4444'
}

function overallRating(tools) {
  const w = { average: 0.25, power: 0.25, speed: 0.15, fielding: 0.2, arm: 0.15 }
  return Math.round(Object.entries(tools).reduce((s, [k, v]) => s + v * (w[k] ?? 0.2), 0))
}

// ─── Diamond Legends brand mark (SVG, era-aware) ────────────────────────────

function DLMark({ era }) {
  if (era === 'deadball') {
    return (
      <svg width="22" height="22" viewBox="0 0 22 22">
        <polygon points="11,2 20,11 11,20 2,11" fill="none" stroke="rgba(255,255,255,0.35)" strokeWidth="1" />
        <text x="11" y="15" textAnchor="middle" fill="rgba(255,255,255,0.35)" fontSize="5" fontFamily="serif">©DL</text>
      </svg>
    )
  }
  if (era === 'modern') {
    return (
      <svg width="26" height="26" viewBox="0 0 26 26">
        <polygon points="13,2 24,13 13,24 2,13" fill="none" stroke="#d4a520" strokeWidth="1.5" />
        <text x="13" y="17" textAnchor="middle" fill="#d4a520" fontSize="6" fontFamily="Arial, sans-serif" fontWeight="bold">DL</text>
      </svg>
    )
  }
  // golden + hardball — white outline diamond with DL
  return (
    <svg width="24" height="24" viewBox="0 0 24 24">
      <polygon points="12,2 22,12 12,22 2,12" fill="none" stroke="rgba(255,255,255,0.7)" strokeWidth="1.2" />
      <text x="12" y="16" textAnchor="middle" fill="rgba(255,255,255,0.7)" fontSize="5.5" fontFamily="Arial, sans-serif" fontWeight="bold">DL</text>
    </svg>
  )
}

// TeamLogo is imported from ./TeamLogo — loads SVG placeholders or approved PNGs

// ─── Portrait image with graceful fallback ────────────────────────────────────
// Tries /portraits/{cardId}.png (generated by pipeline/portrait_workflow.py),
// then card.art, then renders the era placeholder passed as `fallback`.
function PortraitImg({ card, imgStyle = {}, fallback }) {
  const [failed, setFailed] = useState(false)
  const src = card.art || `/portraits/${card.id}.png`
  if (failed) return fallback
  return (
    <img
      src={src}
      alt={card.name}
      style={{ width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'top center', ...imgStyle }}
      onError={() => setFailed(true)}
    />
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// ERA CARD FRONTS
// ═══════════════════════════════════════════════════════════════════════════════

// ─── 1915 Deadball front ─────────────────────────────────────────────────────
function DeadballFront({ card, team, overall, rarity }) {
  return (
    <div style={{
      width: '100%', height: '100%',
      background: team.primary,
      border: `5px solid #e8e0d0`,
      borderRadius: '8px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', position: 'relative',
      fontFamily: "'Playfair Display', Georgia, serif",
      boxShadow: `inset 0 0 0 1px rgba(0,0,0,0.15), ${rarity.glow}`,
    }}>
      {/* Corner rivets */}
      {[[0,0],[0,1],[1,0],[1,1]].map(([row, col], i) => (
        <div key={i} style={{
          position: 'absolute',
          top: row === 0 ? '5px' : undefined,
          bottom: row === 1 ? '5px' : undefined,
          left: col === 0 ? '5px' : undefined,
          right: col === 1 ? '5px' : undefined,
          width: '9px', height: '9px', borderRadius: '50%',
          background: '#e8e0d0', border: '1px solid rgba(0,0,0,0.35)',
          boxShadow: 'inset 0 1px 2px rgba(0,0,0,0.3)',
          zIndex: 2,
        }} />
      ))}

      {/* Brand header — large, black, like Cracker Jack */}
      <div style={{
        textAlign: 'center',
        padding: '10px 20px 5px',
        flexShrink: 0,
      }}>
        <div style={{
          color: '#111',
          fontSize: '1.05rem',
          fontWeight: 900,
          fontFamily: "'Playfair Display', Georgia, serif",
          fontStyle: 'italic',
          lineHeight: 1,
          letterSpacing: '0.01em',
          textShadow: '0 1px 0 rgba(255,255,255,0.15)',
        }}>
          Diamond Legends
        </div>
        <div style={{
          color: '#111',
          fontSize: '0.52rem',
          fontWeight: 700,
          letterSpacing: '0.22em',
          textTransform: 'uppercase',
          marginTop: '2px',
          fontFamily: 'Arial Black, Arial, sans-serif',
        }}>
          Ball Players
        </div>
      </div>

      {/* Art area — full bleed against team color, no oval */}
      <div style={{ flex: 1, position: 'relative', overflow: 'hidden', margin: '6px 10px 0' }}>
        <PortraitImg
          card={card}
          imgStyle={{
            objectPosition: 'top center',
          }}
          fallback={
            <div style={{
              width: '100%', height: '100%',
              background: 'linear-gradient(180deg, #b89a6a 0%, #8b7050 35%, #5c4530 70%, #3a2a18 100%)',
              display: 'flex', flexDirection: 'column',
              alignItems: 'center', justifyContent: 'flex-end',
              position: 'relative', overflow: 'hidden',
            }}>
              {/* Sepia vignette */}
              <div style={{
                position: 'absolute', inset: 0,
                background: 'radial-gradient(ellipse at 50% 30%, transparent 20%, rgba(0,0,0,0.45) 100%)',
                pointerEvents: 'none',
              }}/>
              {/* Vintage scratch texture lines */}
              <div style={{
                position: 'absolute', inset: 0, opacity: 0.06,
                backgroundImage: 'repeating-linear-gradient(0deg, transparent, transparent 3px, rgba(255,255,255,0.5) 3px, rgba(255,255,255,0.5) 4px)',
                pointerEvents: 'none',
              }}/>
              {/* Player silhouette SVG */}
              <svg viewBox="0 0 100 130" style={{ width: '88%', height: '88%', position: 'absolute', top: '5%', opacity: 0.28 }}>
                {/* Head */}
                <ellipse cx="50" cy="24" rx="12" ry="13" fill="#1a0e06"/>
                {/* Cap */}
                <ellipse cx="50" cy="14" rx="16" ry="6" fill="#1a0e06"/>
                <rect x="34" y="11" width="32" height="6" rx="2" fill="#1a0e06"/>
                <rect x="28" y="14" width="10" height="3" rx="1" fill="#1a0e06"/>
                {/* Neck */}
                <rect x="45" y="36" width="10" height="8" rx="3" fill="#1a0e06"/>
                {/* Torso / uniform */}
                <path d="M 26 44 Q 32 38 50 42 Q 68 38 74 44 L 70 98 Q 60 94 50 95 Q 40 94 30 98 Z" fill="#1a0e06"/>
                {/* Belt */}
                <rect x="30" y="76" width="40" height="5" rx="1" fill="#0a0604"/>
                {/* Batting arms - raised */}
                <path d="M 72 52 Q 80 46 86 42 Q 90 40 88 44 Q 84 50 76 58" stroke="#1a0e06" strokeWidth="8" fill="none" strokeLinecap="round"/>
                <path d="M 28 52 Q 20 54 16 60" stroke="#1a0e06" strokeWidth="7" fill="none" strokeLinecap="round"/>
                {/* Bat */}
                <path d="M 85 43 Q 95 34 98 28 Q 99 25 97 27 Q 92 32 86 41" stroke="#1a0e06" strokeWidth="4" fill="none" strokeLinecap="round"/>
                <line x1="97" y1="28" x2="102" y2="22" stroke="#1a0e06" strokeWidth="2.5" strokeLinecap="round"/>
              </svg>
              {/* Initials at bottom */}
              <div style={{
                position: 'relative',
                zIndex: 1,
                marginBottom: '8%',
                fontSize: '1.5rem',
                fontWeight: 900,
                fontFamily: 'Georgia, serif',
                fontStyle: 'italic',
                color: 'rgba(240,220,180,0.55)',
                letterSpacing: '0.12em',
                textShadow: '0 1px 4px rgba(0,0,0,0.5)',
              }}>
                {card.name.split(' ').filter(w => !w.startsWith('"')).map(w => w[0]).join('').slice(0,2)}
              </div>
            </div>
          }
        />
        {/* Overall badge */}
        <div style={{
          position: 'absolute', top: '4px', right: '4px',
          background: 'rgba(0,0,0,0.65)', border: `1px solid ${rarity.color}`,
          borderRadius: '4px', padding: '2px 5px', textAlign: 'center',
        }}>
          <div style={{ color: rarity.color, fontSize: '0.9rem', fontWeight: 900, fontFamily: 'monospace', lineHeight: 1 }}>{overall}</div>
          <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: '0.4rem', letterSpacing: '0.1em' }}>OVR</div>
        </div>
        {/* DL watermark */}
        <div style={{ position: 'absolute', top: '4px', left: '4px' }}>
          <DLMark era="deadball" />
        </div>
      </div>

      {/* Cream/parchment name plate — like the Cracker Jack footer */}
      <div style={{
        background: '#f0ece0',
        borderTop: '2px solid rgba(0,0,0,0.25)',
        padding: '5px 10px 7px',
        textAlign: 'center',
        flexShrink: 0,
      }}>
        <div style={{
          color: '#1a1008',
          fontSize: '0.7rem',
          fontWeight: 700,
          letterSpacing: '0.08em',
          lineHeight: 1.1,
          fontFamily: "'Playfair Display', Georgia, serif",
        }}>
          {card.name.replace(/"/g, '').replace(/  +/g, ' ').toUpperCase()}
        </div>
        <div style={{
          color: '#3a2a12',
          fontSize: '0.5rem',
          letterSpacing: '0.12em',
          marginTop: '2px',
          fontFamily: 'Arial, sans-serif',
        }}>
          {team.city.toUpperCase()} · {team.name.toUpperCase()}
        </div>
        {card.trait && (
          <div style={{
            display: 'inline-block', marginTop: '3px',
            background: 'rgba(26,16,8,0.1)', border: '1px solid rgba(26,16,8,0.25)',
            borderRadius: '99px', padding: '1px 7px',
            color: '#3a2a12', fontSize: '0.45rem', letterSpacing: '0.14em',
            textTransform: 'uppercase', fontFamily: 'monospace',
          }}>{card.trait}</div>
        )}
      </div>
    </div>
  )
}

// ─── 1958 Golden Age front ───────────────────────────────────────────────────
function GoldenFront({ card, team, overall, rarity }) {
  // Strip nickname (quoted text), keep only first + last name
  const nameParts = card.name.replace(/"[^"]*"/g, '').replace(/  +/g, ' ').trim().split(' ').filter(Boolean)
  const displayName = nameParts.length >= 2 ? `${nameParts[0]} ${nameParts[nameParts.length - 1]}` : nameParts[0] || ''

  return (
    <div style={{
      width: '100%', height: '100%',
      background: '#e8e4dc',
      border: `5px solid #ccc8be`,
      borderRadius: '5px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', position: 'relative',
      boxShadow: `0 2px 8px rgba(0,0,0,0.3), ${rarity.glow}`,
    }}>
      {/* Art — full bleed, name will hover over the top */}
      <div style={{ flex: 1, position: 'relative', overflow: 'hidden', background: '#b8ae9a' }}>
        <PortraitImg
          card={card}
          imgStyle={{ filter: 'saturate(0.8) brightness(1.05) sepia(0.1)' }}
          fallback={
            <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: team.primary }}>
              <div style={{ fontSize: '2.5rem', opacity: 0.25 }}>⚾</div>
              <div style={{ color: '#fff', fontSize: '1.6rem', fontWeight: 900, fontFamily: 'Arial Black', opacity: 0.35 }}>
                {displayName.split(' ').map(w => w[0]).join('').slice(0, 2)}
              </div>
            </div>
          }
        />

        {/* Name overlaid on top of art — team color backing fades into photo */}
        <div style={{
          position: 'absolute', top: 0, left: 0, right: 0,
          background: `linear-gradient(to bottom, ${team.primary}f0 55%, ${team.primary}00 100%)`,
          padding: '8px 10px 22px',
        }}>
          <div style={{
            color: team.secondary,
            fontSize: '1.25rem',
            fontWeight: 900,
            fontFamily: "'Playfair Display', Georgia, serif",
            fontStyle: 'italic',
            lineHeight: 1.0,
            letterSpacing: '0.01em',
            textShadow: `0 1px 3px rgba(0,0,0,0.4)`,
          }}>
            {displayName}
          </div>
        </div>

        {/* DL mark — top right */}
        <div style={{ position: 'absolute', top: '6px', right: '6px' }}>
          <DLMark era="golden" />
        </div>

        {/* Overall badge */}
        <div style={{
          position: 'absolute', top: '6px', right: '30px',
          background: 'rgba(0,0,0,0.72)', border: `1px solid ${rarity.color}`,
          borderRadius: '4px', padding: '2px 5px', textAlign: 'center',
        }}>
          <div style={{ color: rarity.color, fontSize: '0.95rem', fontWeight: 900, fontFamily: 'monospace', lineHeight: 1 }}>{overall}</div>
          <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: '0.4rem', letterSpacing: '0.1em' }}>OVR</div>
        </div>
      </div>

      {/* Bottom strip: position left, team name right — like 1958 Topps */}
      <div style={{
        background: team.primary,
        padding: '4px 8px',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        flexShrink: 0,
      }}>
        <div style={{
          color: team.secondary,
          fontSize: '0.6rem',
          fontWeight: 900,
          fontFamily: 'Arial Black, Arial, sans-serif',
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
        }}>
          {card.position}
        </div>
        <div style={{
          color: team.secondary,
          fontSize: '0.6rem',
          fontWeight: 900,
          fontFamily: 'Arial Black, Arial, sans-serif',
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
        }}>
          {team.city} {team.name}
        </div>
        {card.trait && (
          <div style={{
            background: 'rgba(0,0,0,0.25)',
            borderRadius: '3px',
            padding: '1px 5px',
            color: team.secondary,
            fontSize: '0.42rem',
            fontFamily: 'monospace',
            letterSpacing: '0.1em',
            textTransform: 'uppercase',
          }}>{card.trait}</div>
        )}
      </div>
    </div>
  )
}

// ─── 1986 Hardball front ─────────────────────────────────────────────────────
function HardballFront({ card, team, overall, rarity }) {
  const nameParts = card.name.replace(/"[^"]*"/g, '').replace(/  +/g, ' ').trim().split(' ').filter(Boolean)
  const displayName = nameParts.length >= 2 ? `${nameParts[0]} ${nameParts[nameParts.length - 1]}` : nameParts[0] || ''
  return (
    <div style={{
      width: '100%', height: '100%',
      background: '#111',
      border: `4px solid #111`,
      borderRadius: '5px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', position: 'relative',
      boxShadow: `0 2px 10px rgba(0,0,0,0.4), ${rarity.glow}`,
    }}>
      {/* Team name — huge, centered, like MARINERS on 1986 Topps */}
      <div style={{
        background: '#111',
        padding: '5px 8px 3px',
        flexShrink: 0,
        position: 'relative',
        textAlign: 'center',
      }}>
        <div style={{
          color: team.primary,
          fontSize: '1.5rem',
          fontWeight: 900,
          fontFamily: 'Arial Black, Arial, sans-serif',
          letterSpacing: '0.04em',
          textTransform: 'uppercase',
          lineHeight: 1,
          textShadow: `0 0 16px ${team.primary}60`,
        }}>
          {team.name}
        </div>
        <div style={{ position: 'absolute', top: '6px', right: '6px' }}>
          <DLMark era="hardball" />
        </div>
      </div>

      {/* Art — white inner border like 1986 Topps */}
      <div style={{ flex: 1, position: 'relative', overflow: 'hidden', margin: '0 4px', background: '#666' }}>
        <PortraitImg
          card={card}
          imgStyle={{ filter: 'saturate(1.15) contrast(1.05)' }}
          fallback={
            <div style={{ width: '100%', height: '100%', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(160deg, #777 0%, #444 100%)' }}>
              <div style={{ fontSize: '2.5rem', opacity: 0.3, color: '#fff' }}>⚾</div>
              <div style={{ color: 'rgba(255,255,255,0.3)', fontSize: '1.6rem', fontWeight: 900, fontFamily: 'Arial Black' }}>
                {displayName.split(' ').map(w => w[0]).join('').slice(0, 2)}
              </div>
            </div>
          }
        />
        {/* Overall badge */}
        <div style={{
          position: 'absolute', top: '6px', right: '6px',
          background: 'rgba(0,0,0,0.78)', border: `1px solid ${rarity.color}`,
          borderRadius: '4px', padding: '2px 5px', textAlign: 'center',
        }}>
          <div style={{ color: rarity.color, fontSize: '0.95rem', fontWeight: 900, fontFamily: 'monospace', lineHeight: 1 }}>{overall}</div>
          <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: '0.4rem', letterSpacing: '0.1em' }}>OVR</div>
        </div>
        {/* Position circle — bottom left, like 1986 Topps */}
        <div style={{
          position: 'absolute', bottom: '6px', left: '6px',
          width: '22px', height: '22px', borderRadius: '50%',
          background: team.primary,
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          border: '1.5px solid rgba(255,255,255,0.4)',
        }}>
          <span style={{ fontSize: '0.48rem', fontWeight: 900, color: team.secondary, fontFamily: 'Arial Black' }}>{card.position}</span>
        </div>
      </div>

      {/* White name footer — large player name, like 1986 Topps */}
      <div style={{
        background: '#f4f4f4',
        padding: '4px 8px 5px',
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        flexShrink: 0,
        margin: '0 4px',
        borderTop: `3px solid ${team.primary}`,
      }}>
        <div style={{
          fontSize: '0.75rem',
          fontWeight: 900,
          fontFamily: 'Arial Black, Arial, sans-serif',
          color: '#111',
          letterSpacing: '0.05em',
          textTransform: 'uppercase',
          lineHeight: 1,
        }}>
          {displayName}
        </div>
        {/* Trait — bright team colors so it reads on white */}
        {card.trait && (
          <div style={{
            background: team.primary,
            borderRadius: '3px',
            padding: '2px 6px',
            color: team.secondary,
            fontSize: '0.44rem',
            fontFamily: 'Arial Black, Arial, sans-serif',
            letterSpacing: '0.06em',
            textTransform: 'uppercase',
            fontWeight: 900,
            whiteSpace: 'nowrap',
          }}>{card.trait}</div>
        )}
      </div>
    </div>
  )
}

// ─── 2025 Modern front ───────────────────────────────────────────────────────
function ModernFront({ card, team, overall, rarity }) {
  const isLegend = rarity === RARITY.legend
  const nameParts = card.name.replace(/"[^"]*"/g, '').replace(/  +/g, ' ').trim().split(' ').filter(Boolean)
  const displayName = nameParts.length >= 2 ? `${nameParts[0]} ${nameParts[nameParts.length - 1]}` : nameParts[0] || ''

  return (
    <div style={{
      width: '100%', height: '100%',
      background: '#fff',
      border: `3px solid #d8d8e0`,
      borderRadius: '10px',
      overflow: 'hidden', position: 'relative',
      boxShadow: isLegend
        ? `0 4px 20px rgba(0,0,0,0.3), 0 0 0 1px rgba(245,158,11,0.5), ${rarity.glow}`
        : `0 4px 16px rgba(0,0,0,0.2), ${rarity.glow}`,
    }}>

      {/* Full-bleed photo — fills entire card */}
      <div style={{ position: 'absolute', inset: 0, background: '#aaa' }}>
        <PortraitImg
          card={card}
          imgStyle={{}}
          fallback={
            <div style={{ width: '100%', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(160deg, #bbb 0%, #888 100%)' }}>
              <div style={{ fontSize: '2.8rem', opacity: 0.25, color: '#fff' }}>⚾</div>
            </div>
          }
        />
        {isLegend && (
          <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(135deg, transparent 30%, rgba(255,215,0,0.08) 50%, transparent 70%)', pointerEvents: 'none' }} />
        )}
      </div>

      {/* L-frame — left bar */}
      <div style={{
        position: 'absolute', left: 0, top: 0, bottom: 0,
        width: '32px',
        background: 'rgba(8,8,8,0.88)',
        borderRadius: '8px 0 0 8px',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        zIndex: 2,
      }}>
        {/* Team name — large vertical, team primary color */}
        <div style={{
          writingMode: 'vertical-rl',
          transform: 'rotate(180deg)',
          color: team.primary,
          fontSize: '1.05rem',
          fontWeight: 900,
          fontFamily: 'Arial Black, Arial, sans-serif',
          letterSpacing: '0.14em',
          textTransform: 'uppercase',
          lineHeight: 1,
          textShadow: `0 0 18px ${team.primary}70`,
          // Subtle outline for depth
          WebkitTextStroke: `0.5px ${team.primary}`,
        }}>
          {team.name}
        </div>
      </div>

      {/* L-frame — bottom bar (starts where left bar ends) */}
      <div style={{
        position: 'absolute', left: '32px', right: 0, bottom: 0,
        height: '36px',
        background: 'rgba(8,8,8,0.88)',
        borderRadius: '0 0 8px 0',
        display: 'flex', alignItems: 'center',
        paddingLeft: '18px', paddingRight: '8px',
        gap: '6px',
        zIndex: 2,
      }}>
        {/* Player name */}
        <div style={{
          color: '#f0d060',
          fontSize: '0.78rem',
          fontWeight: 900,
          fontFamily: 'Arial Black, Arial, sans-serif',
          letterSpacing: '0.06em',
          textTransform: 'uppercase',
          flex: 1,
          lineHeight: 1,
        }}>
          {displayName}
        </div>
        {/* Trait pill */}
        {card.trait && (
          <div style={{
            background: team.primary, borderRadius: '3px', padding: '2px 5px',
            color: team.secondary, fontSize: '0.38rem',
            fontFamily: 'Arial Black, Arial, sans-serif',
            letterSpacing: '0.06em', textTransform: 'uppercase', fontWeight: 900,
            whiteSpace: 'nowrap',
          }}>{card.trait}</div>
        )}
        {/* Position — diamond shape */}
        <div style={{
          width: '20px', height: '20px',
          border: `2px solid ${team.primary}`,
          transform: 'rotate(45deg)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          flexShrink: 0,
          borderRadius: '2px',
        }}>
          <span style={{
            transform: 'rotate(-45deg)',
            fontSize: '0.38rem', color: team.primary,
            fontFamily: 'Arial Black', fontWeight: 900,
          }}>{card.position}</span>
        </div>
      </div>

      {/* L-frame corner filler — bridges left bar and bottom bar */}
      <div style={{
        position: 'absolute', left: 0, bottom: 0,
        width: '32px', height: '36px',
        background: 'rgba(8,8,8,0.88)',
        zIndex: 3,
      }} />

      {/* Team logo — sticker overlapping the L-corner */}
      <div style={{
        position: 'absolute',
        bottom: '22px', left: '8px',
        zIndex: 5,
        filter: 'drop-shadow(0 3px 6px rgba(0,0,0,0.8)) drop-shadow(0 0 1px rgba(255,255,255,0.3))',
      }}>
        <TeamLogo franchiseId={card.franchiseId} size={52} />
      </div>

      {/* OVR badge — top right */}
      <div style={{
        position: 'absolute', top: '8px', right: '8px',
        background: 'rgba(0,0,0,0.78)', border: `1px solid ${rarity.color}`,
        borderRadius: '4px', padding: '2px 5px', textAlign: 'center',
        zIndex: 4,
      }}>
        <div style={{ color: rarity.color, fontSize: '0.95rem', fontWeight: 900, fontFamily: 'monospace', lineHeight: 1 }}>{overall}</div>
        <div style={{ color: 'rgba(255,255,255,0.5)', fontSize: '0.4rem', letterSpacing: '0.1em' }}>OVR</div>
      </div>

      {/* DL mark — top right */}
      <div style={{ position: 'absolute', top: '6px', right: '38px', zIndex: 4 }}>
        <DLMark era="modern" />
      </div>
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// ERA CARD BACKS
// ═══════════════════════════════════════════════════════════════════════════════

const STAT_COLS = [
  { key: 'g',   label: 'G' },
  { key: 'ab',  label: 'AB' },
  { key: 'h',   label: 'H' },
  { key: 'r',   label: 'R' },
  { key: 'rbi', label: 'RBI' },
  { key: 'avg', label: 'AVG' },
  { key: 'slg', label: 'SLG' },
]

const PITCHER_COLS = [
  { key: 'g',   label: 'G' },
]

function isPitcher(card) {
  return card.positions.every(p => ['SP','RP','CP'].includes(p))
}

function StatTable({ card, team, textColor, headerBg, headerText, borderColor, altRowBg }) {
  const pitcher = isPitcher(card)
  const statCols = pitcher ? PITCHER_COLS : STAT_COLS
  const allCols = [...statCols, ...TOOL_COLS]

  return (
    <div style={{ overflowX: 'auto' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.42rem', fontFamily: 'monospace' }}>
        <thead>
          <tr style={{ background: headerBg }}>
            <th style={{ padding: '2px 3px', textAlign: 'left', color: headerText, letterSpacing: '0.05em', borderRight: `1px solid ${borderColor}` }}>YR</th>
            <th style={{ padding: '2px 3px', textAlign: 'left', color: headerText, letterSpacing: '0.05em', borderRight: `1px solid ${borderColor}` }}>CLUB</th>
            {allCols.map(c => (
              <th key={c.key} style={{ padding: '2px 3px', textAlign: 'center', color: headerText, letterSpacing: '0.04em', borderRight: `1px solid ${borderColor}` }}>
                {c.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {card.stats.map((row, i) => (
            <tr key={row.season} style={{ background: i % 2 === 1 ? altRowBg : 'transparent' }}>
              <td style={{ padding: '2px 3px', color: textColor, borderRight: `1px solid ${borderColor}` }}>{row.season}</td>
              <td style={{ padding: '2px 3px', color: textColor, borderRight: `1px solid ${borderColor}` }}>{row.team}</td>
              {allCols.map(c => (
                <td key={c.key} style={{
                  padding: '2px 3px', textAlign: 'center', borderRight: `1px solid ${borderColor}`,
                  color: c.key.endsWith('_tool') ? toolColor(row[c.key] ?? 0) : textColor,
                  fontWeight: c.key.endsWith('_tool') ? 700 : 400,
                }}>
                  {row[c.key] ?? '—'}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

// ─── 1915 Deadball back ──────────────────────────────────────────────────────
function DeadballBack({ card, team, overall, rarity }) {
  return (
    <div style={{
      width: '100%', height: '100%',
      background: '#f2ead8',
      border: `6px solid #e8e0d0`,
      borderRadius: '8px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', padding: '8px 10px',
      fontFamily: "'Playfair Display', Georgia, serif",
      boxShadow: `inset 0 0 0 2px rgba(0,0,0,0.08)`,
    }}>
      {/* Card number — top center */}
      <div style={{ textAlign: 'center', marginBottom: '4px' }}>
        <span style={{ fontSize: '0.9rem', fontWeight: 700, color: '#3a2810', fontFamily: 'Georgia, serif' }}>
          {card.cardNumber}
        </span>
      </div>

      {/* Bio */}
      <p style={{
        fontSize: '0.48rem', color: '#3a2810', lineHeight: 1.6,
        margin: '0 0 6px', fontStyle: 'italic',
      }}>
        {card.name}, {card.position === 'SP' || card.position === 'RP' ? 'pitcher' : card.position.toLowerCase()} for the {team.city} {team.name}, was born in {card.birthplace}. Standing {card.height} and weighing {card.weight} lbs., he bats {card.bats === 'B' ? 'both ways' : card.bats === 'L' ? 'left-handed' : 'right-handed'} and throws from the {card.throws === 'L' ? 'port' : 'starboard'} side. His Era Trait is known as <strong>{card.trait}</strong>.
      </p>

      <p style={{ fontSize: '0.46rem', color: '#5a3a18', lineHeight: 1.5, margin: '0 0 6px', fontStyle: 'italic', opacity: 0.85 }}>
        "{card.flavorText}"
      </p>

      {/* Stats */}
      <div style={{ flex: 1 }}>
        <StatTable card={card} team={team}
          textColor="#3a2810" headerBg="#8b6340" headerText="#f5f0e8"
          borderColor="rgba(139,99,64,0.2)" altRowBg="rgba(139,99,64,0.08)"
        />
      </div>

      {/* Footer */}
      <div style={{ marginTop: '4px', borderTop: '1px solid rgba(58,40,16,0.2)', paddingTop: '4px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ fontSize: '0.42rem', color: 'rgba(58,40,16,0.5)', fontFamily: 'monospace', letterSpacing: '0.08em' }}>
          DIAMOND LEGENDS CARD CO. · {card.rarity.toUpperCase()} SERIES
        </div>
        <div style={{ color: rarity.color, fontSize: '0.42rem', fontFamily: 'monospace', letterSpacing: '0.1em' }}>{rarity.label}</div>
      </div>
    </div>
  )
}

// ─── 1958 Golden Age back ────────────────────────────────────────────────────
function GoldenBack({ card, team, overall, rarity }) {
  return (
    <div style={{
      width: '100%', height: '100%',
      background: team.primary,
      border: `4px solid #d8d0c4`,
      borderRadius: '6px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', padding: '6px 8px',
      fontFamily: 'Arial, sans-serif',
    }}>
      {/* Card number — pennant star shape */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '6px', marginBottom: '4px' }}>
        <div style={{
          width: '24px', height: '24px', flexShrink: 0,
          background: team.secondary, clipPath: 'polygon(50% 0%,61% 35%,98% 35%,68% 57%,79% 91%,50% 70%,21% 91%,32% 57%,2% 35%,39% 35%)',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
        }}>
          <span style={{ fontSize: '0.48rem', fontWeight: 900, color: team.primary, marginTop: '4px' }}>{card.cardNumber.replace('#','')}</span>
        </div>
        <div>
          <div style={{ color: team.secondary, fontSize: '0.68rem', fontWeight: 900, letterSpacing: '0.06em', lineHeight: 1 }}>{card.name.split('"')[0].trim().toUpperCase()}</div>
          <div style={{ color: 'rgba(255,255,255,0.65)', fontSize: '0.44rem', letterSpacing: '0.1em' }}>
            {card.position} · {team.city} {team.name}
          </div>
        </div>
        <div style={{ marginLeft: 'auto', textAlign: 'right' }}>
          <div style={{ color: rarity.color, fontSize: '0.55rem', fontFamily: 'monospace', fontWeight: 700 }}>{overall}</div>
          <div style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.38rem', letterSpacing: '0.1em' }}>OVR</div>
        </div>
      </div>

      {/* Bio */}
      <p style={{ fontSize: '0.44rem', color: 'rgba(255,255,255,0.85)', lineHeight: 1.55, margin: '0 0 5px', fontStyle: 'italic' }}>
        {card.flavorText} — Bats: {card.bats} · Throws: {card.throws} · {card.height}, {card.weight} lbs. · Born: {card.birthplace}
      </p>

      {/* Stats */}
      <div style={{ flex: 1 }}>
        <div style={{ color: team.secondary, fontSize: '0.48rem', fontWeight: 700, letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '2px', borderBottom: `1px solid rgba(255,255,255,0.2)`, paddingBottom: '2px' }}>
          {card.name.split('"')[0].trim().toUpperCase()} RECORD
        </div>
        <StatTable card={card} team={team}
          textColor="rgba(255,255,255,0.9)" headerBg="rgba(0,0,0,0.3)" headerText={team.secondary}
          borderColor="rgba(255,255,255,0.1)" altRowBg="rgba(0,0,0,0.15)"
        />
      </div>

      {/* Footer */}
      <div style={{ marginTop: '4px', display: 'flex', justifyContent: 'space-between' }}>
        <div style={{ fontSize: '0.38rem', color: 'rgba(255,255,255,0.4)', fontFamily: 'monospace', letterSpacing: '0.06em' }}>
          DIAMOND LEGENDS · {card.rarity.toUpperCase()}
        </div>
        <div style={{ color: rarity.color, fontSize: '0.42rem', fontFamily: 'monospace' }}>{rarity.label}</div>
      </div>
    </div>
  )
}

// ─── 1986 Hardball back ──────────────────────────────────────────────────────
function HardballBack({ card, team, overall, rarity }) {
  return (
    <div style={{
      width: '100%', height: '100%',
      background: team.primary,
      border: `4px solid #e0e0e0`,
      borderRadius: '5px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', padding: '0',
      fontFamily: 'Arial, Helvetica, sans-serif',
    }}>
      {/* Header block */}
      <div style={{ background: '#111', padding: '4px 8px', display: 'flex', alignItems: 'center', gap: '6px' }}>
        <div style={{
          background: team.secondary, color: team.primary,
          fontSize: '0.6rem', fontWeight: 900, fontFamily: 'Arial Black',
          padding: '1px 6px', borderRadius: '2px', flexShrink: 0,
        }}>{card.cardNumber}</div>
        <div style={{ flex: 1 }}>
          <div style={{ color: '#fff', fontSize: '0.65rem', fontWeight: 900, fontFamily: 'Arial Black', letterSpacing: '0.06em', lineHeight: 1 }}>
            {card.name.split('"')[0].trim().toUpperCase()}
          </div>
          <div style={{ color: 'rgba(255,255,255,0.6)', fontSize: '0.42rem', letterSpacing: '0.1em' }}>
            HT: {card.height} · WT: {card.weight} · BATS: {card.bats} · THROWS: {card.throws} · BORN: {card.birthplace}
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ color: rarity.color, fontSize: '0.6rem', fontFamily: 'monospace', fontWeight: 700 }}>{overall}</div>
          <div style={{ color: 'rgba(255,255,255,0.4)', fontSize: '0.36rem' }}>OVR</div>
        </div>
      </div>

      {/* Stats */}
      <div style={{ flex: 1, padding: '5px 8px' }}>
        <div style={{ color: team.secondary, fontSize: '0.46rem', fontWeight: 700, letterSpacing: '0.12em', textTransform: 'uppercase', marginBottom: '3px' }}>
          COMPLETE BATTING RECORD
        </div>
        <StatTable card={card} team={team}
          textColor="rgba(255,255,255,0.9)" headerBg="rgba(0,0,0,0.35)" headerText={team.secondary}
          borderColor="rgba(255,255,255,0.1)" altRowBg="rgba(0,0,0,0.15)"
        />
      </div>

      {/* Highlights */}
      <div style={{ padding: '4px 8px', borderTop: `1px solid rgba(255,255,255,0.15)` }}>
        <p style={{ fontSize: '0.42rem', color: 'rgba(255,255,255,0.8)', lineHeight: 1.5, margin: 0, fontStyle: 'italic' }}>
          {card.flavorText}
        </p>
      </div>

      {/* Footer */}
      <div style={{ padding: '3px 8px', background: 'rgba(0,0,0,0.2)', display: 'flex', justifyContent: 'space-between' }}>
        <div style={{ fontSize: '0.38rem', color: 'rgba(255,255,255,0.4)', fontFamily: 'monospace' }}>DIAMOND LEGENDS · {card.rarity.toUpperCase()}</div>
        <div style={{ color: rarity.color, fontSize: '0.42rem', fontFamily: 'monospace' }}>{rarity.label}</div>
      </div>
    </div>
  )
}

// ─── 2025 Modern back ────────────────────────────────────────────────────────
function ModernBack({ card, team, overall, rarity }) {
  return (
    <div style={{
      width: '100%', height: '100%',
      background: '#f8f9fa',
      border: `3px solid #d0d0d8`,
      borderRadius: '10px',
      display: 'flex', flexDirection: 'column',
      overflow: 'hidden', padding: '0',
      fontFamily: 'Arial, Helvetica, sans-serif',
    }}>
      {/* Header */}
      <div style={{ padding: '6px 8px', background: '#fff', borderBottom: '1px solid #e0e0e8', display: 'flex', alignItems: 'center', gap: '6px' }}>
        <TeamLogo franchiseId={card.franchiseId} size={28} />
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: '0.65rem', fontWeight: 900, fontFamily: 'Arial Black', color: '#111', lineHeight: 1.1 }}>
            {card.name.split('"')[0].trim().toUpperCase()}
          </div>
          <div style={{ fontSize: '0.42rem', color: '#666', letterSpacing: '0.08em' }}>
            {team.city} {team.name.toUpperCase()} · {card.position} · {card.height}, {card.weight} lbs
          </div>
        </div>
        <div style={{ textAlign: 'right' }}>
          <div style={{ color: rarity.color, fontSize: '0.62rem', fontFamily: 'monospace', fontWeight: 700 }}>{overall}</div>
          <div style={{ color: '#999', fontSize: '0.36rem' }}>OVR</div>
        </div>
        <div style={{ textAlign: 'right', color: '#aaa', fontSize: '0.42rem', fontFamily: 'monospace' }}>
          <div>{card.cardNumber}</div>
          <div style={{ fontSize: '0.36rem', letterSpacing: '0.08em' }}>SERIES ONE</div>
        </div>
      </div>

      {/* Stats */}
      <div style={{ flex: 1, padding: '5px 8px' }}>
        <div style={{ fontSize: '0.44rem', fontWeight: 700, color: '#444', letterSpacing: '0.1em', textTransform: 'uppercase', marginBottom: '3px', borderBottom: '1px solid #e0e0e8', paddingBottom: '2px' }}>
          MAJOR LEAGUE RECORD
        </div>
        <StatTable card={card} team={team}
          textColor="#333" headerBg={team.primary} headerText={team.secondary}
          borderColor="#e8e8f0" altRowBg="rgba(0,0,0,0.03)"
        />
      </div>

      {/* Narrative */}
      <div style={{ padding: '4px 8px', borderTop: '1px solid #e0e0e8' }}>
        <p style={{ fontSize: '0.42rem', color: '#555', lineHeight: 1.55, margin: 0 }}>
          {card.flavorText} — Bats: {card.bats} · Throws: {card.throws} · Born: {card.birthplace}
        </p>
      </div>

      {/* Footer */}
      <div style={{ padding: '3px 8px', background: '#f0f0f4', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div style={{ fontSize: '0.38rem', color: '#aaa', fontFamily: 'monospace', letterSpacing: '0.06em' }}>
          © DIAMOND LEGENDS CARD CO. ALL RIGHTS RESERVED.
        </div>
        <div style={{ color: rarity.color, fontSize: '0.42rem', fontFamily: 'monospace', fontWeight: 700 }}>{rarity.label}</div>
      </div>
    </div>
  )
}

// ═══════════════════════════════════════════════════════════════════════════════
// CARD ROUTER
// ═══════════════════════════════════════════════════════════════════════════════

const FRONT = { deadball: DeadballFront, golden: GoldenFront, hardball: HardballFront, modern: ModernFront }
const BACK  = { deadball: DeadballBack,  golden: GoldenBack,  hardball: HardballBack,  modern: ModernBack  }

const SIZES = {
  sm: { width: 150, height: 210 },
  md: { width: 200, height: 280 },
  lg: { width: 260, height: 364 },
  xl: { width: 320, height: 448 },
}

export default function Card({ card, size = 'md' }) {
  const [expanded, setExpanded] = useState(false)
  const team    = getTeamForEra(card.franchiseId, card.era) ?? { city: 'Unknown', name: 'Team', primary: '#333', secondary: '#fff', abbreviation: '??' }
  const rarity  = RARITY[card.rarity] ?? RARITY.common
  const overall = overallRating(card.tools)
  const { width, height } = SIZES[size] ?? SIZES.md

  const Front = FRONT[card.era] ?? DeadballFront
  const props = { card, team, overall, rarity }

  useEffect(() => {
    if (!expanded) return
    const onKey = (e) => { if (e.key === 'Escape') setExpanded(false) }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [expanded])

  return (
    <>
      <motion.div
        style={{ width, height, cursor: 'pointer', flexShrink: 0 }}
        onClick={() => setExpanded(true)}
        title="Click to expand"
        whileHover={{ scale: 1.03 }}
        whileTap={{ scale: 0.97 }}
        transition={{ type: 'spring', stiffness: 400, damping: 25 }}
      >
        <Front {...props} />
      </motion.div>

      {createPortal(
        <AnimatePresence>
          {expanded && (
            <motion.div
              key="card-overlay"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              transition={{ duration: 0.2 }}
              style={{
                position: 'fixed', inset: 0,
                background: 'rgba(0,0,0,0.78)',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                zIndex: 1000,
                backdropFilter: 'blur(4px)',
              }}
              onClick={() => setExpanded(false)}
            >
              <motion.div
                initial={{ opacity: 0, scale: 0.65, rotate: 8 }}
                animate={{ opacity: 1, scale: 1, rotate: 0 }}
                exit={{ opacity: 0, scale: 0.65, rotate: 8 }}
                transition={{ type: 'spring', stiffness: 320, damping: 28 }}
                onClick={e => e.stopPropagation()}
              >
                <CardExpanded {...props} onClose={() => setExpanded(false)} />
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>,
        document.body
      )}
    </>
  )
}
